set_property PACKAGE_PIN Y18 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN Y19 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN Y16 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN Y17 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]

set_property PACKAGE_PIN U18 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN U19 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN W18 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN W19 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]

set_property PACKAGE_PIN W14 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN Y14 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN T11 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN T10 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]

set_property PACKAGE_PIN V16 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]

set_property PACKAGE_PIN W16 [get_ports vsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]